server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: upload-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/audio/upload/**
            - id: transcription-service
              uri: http://localhost:8082
              predicates:
                - Path=/transcript/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: read
